### ISSUE TITLE
NameError: name 'opentracing' is not defined

### ISSUE THREAD

**Issue by maynewong** [songcser/sanic-ms#5]
I run `BUILD=y PULL=y ./develop/reset.sh`,Then curl http://localhost:8000, server cannot run

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 538, in handle_request
    response = await self._run_request_middleware(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 717, in _run_request_middleware
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/sanicms/server.py", line 56, in cros
    span = before_request(request)
  File "/usr/local/lib/python3.6/site-packages/sanicms/utils.py", line 124, in before_request
    span = opentracing.tracer.start_span(operation_name=handler[0].__name__,
NameError: name 'opentracing' is not defined
```

**Comment by songcser** [comment]
This problem has been solved。
please pull code and run BUILD=y PULL=y ./develop/reset.sh again。
