### ISSUE TITLE
运行examples里的演示代码发现程序不能预期运行

### ISSUE THREAD

**Issue by kirioo** [songcser/sanic-ms#9]
我参照 examples 里的README.md 进行程序运行测试，发现如下错误。
```
Attaching to examples_swagger_1, examples_server_1, examples_db_1, examples_zipkin_1
server_1   | Traceback (most recent call last):
server_1   |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
server_1   |     "__main__", mod_spec)
server_1   |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
server_1   |     exec(code, run_globals)
server_1   |   File "/service/user_service/server.py", line 5, in <module>
server_1   |     from sanicms.server import app
server_1   |   File "/usr/local/lib/python3.6/site-packages/sanicms/server.py", line 29, in <module>
server_1   |     config = load_config()
server_1   |   File "/usr/local/lib/python3.6/site-packages/sanicms/__init__.py", line 9, in load_config
server_1   |     conf.from_pyfile(path)
server_1   |   File "/usr/local/lib/python3.6/site-packages/sanic/config.py", line 80, in from_pyfile
server_1   |     with open(filename) as config_file:
server_1   | FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): 'settings.py'
```
如何解决？

**Comment by songcser** [comment]
代码有更新，还没有跑过，可能配置文件路径错了

**Comment by kirioo** [comment]
目前我这么有个生产环境想投入使用这个框架，期待bug fixed.

**Comment by songcser** [comment]
bug修好了，可以跑一下./develop/cluster.sh这个脚本
